spring.application.name=pulseops
spring.jpa.open-in-view=false

spring.jpa.hibernate.ddl-auto = validate

##Security properties
pulseops.security.jwt.secret=${JWT_SECRET}
pulseops.security.jwt.issuer=pulseops
pulseops.security.jwt.access-token-ttl=3600s

spring.config.import=optional:file:.env[.properties]

server.port=8080

##OpenAPI / Swagger properties
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Maps MY_ADMIN_EMAIL and MY_ADMIN_PASSWORD from the system environment
app.admin.default-email=${ADMIN_EMAIL}
app.admin.default-password=${ADMIN_PASSWORD}
