spring.application.name=pulseops
spring.jpa.open-in-view=false

spring.jpa.hibernate.ddl-auto = validate

##Security properties
pulseops.security.jwt.secret=${JWT_SECRET}
pulseops.security.jwt.issuer=pulseops
pulseops.security.jwt.access-token-ttl=3600s

spring.config.import=optional:file:.env[.properties]
